// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'characterContainer': string;
  'showPinyinCheckbox': string;
}
export const cssExports: CssExports;
export default cssExports;
